(ns jiffy.protocols.format.date-time-formatter
  (:refer-clojure :exclude [format ])
  (:require [clojure.spec.alpha :as s]))

(defprotocol IDateTimeFormatter
  (parse-best [this parse-best--unknown-param-name-1 parse-best--unknown-param-name-2])
  (format [this formatter])
  (get-locale [this])
  (with-locale [this locale])
  (localized-by [this locale])
  (get-decimal-style [this])
  (with-decimal-style [this decimal-style])
  (get-chronology [this])
  (with-chronology [this chrono])
  (get-zone [this])
  (with-zone [this zone])
  (get-resolver-style [this])
  (with-resolver-style [this resolver-style])
  (get-resolver-fields [this])
  (with-resolver-fields [this with-resolver-fields--overloaded-param])
  (format-to [this temporal appendable])
  (parse [this text] [this parse--overloaded-param-1 parse--overloaded-param-2])
  (parse-unresolved [this text position])
  (to-printer-parser [this optional])
  (to-format [this] [this parse-query]))

(s/def ::date-time-formatter #(satisfies? IDateTimeFormatter %))
