(ns jiffy.offset-time-test
  #?(:clj (:require [jiffy.support-clj :refer [test-proto-fn test-proto-fn! test-static-fn test-static-fn!] :as support])
     :cljs (:require [jiffy.support-cljs :refer [test-proto-fn test-proto-fn! test-static-fn test-static-fn!] :as support :include-macros true])))

(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/get-offset)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-offset-same-local)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-offset-same-instant)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/to-local-time)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/get-hour)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/get-minute)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/get-second)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/get-nano)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-hour)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-minute)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-second)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/with-nano)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/truncated-to)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/plus-hours)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/plus-minutes)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/plus-seconds)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/plus-nanos)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/minus-hours)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/minus-minutes)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/minus-seconds)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/minus-nanos)
;; (test-proto-fn! jiffy.offset-time jiffy.protocols.offset-time/format)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/at-date)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/to-epoch-second)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/is-after)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/is-before)
(test-proto-fn jiffy.offset-time jiffy.protocols.offset-time/is-equal)

(test-proto-fn jiffy.offset-time jiffy.protocols.time-comparable/compare-to)

(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal/with)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal/plus)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal/minus)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal/until)

(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-accessor/is-supported)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-accessor/range)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-accessor/get)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-accessor/get-long)
(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-accessor/query)

(test-proto-fn jiffy.offset-time jiffy.protocols.temporal.temporal-adjuster/adjust-into)

;; (test-static-fn! jiffy.offset-time/now)
(test-static-fn jiffy.offset-time/of)
(test-static-fn jiffy.offset-time/of-instant)
(test-static-fn jiffy.offset-time/from)
;; (test-static-fn! jiffy.offset-time/parse)
