(ns jiffy.protocols.local-date-time
  (:require [clojure.spec.alpha :as s]))

;; https://github.com/unofficial-openjdk/openjdk/tree/cec6bec2602578530214b2ce2845a863da563c3d/src/java.base/share/classes/java/time/LocalDateTime.java
(defprotocol ILocalDateTime
  (get-year [this])
  (get-month-value [this])
  (get-month [this])
  (get-day-of-month [this])
  (get-day-of-year [this])
  (get-day-of-week [this])
  (get-hour [this])
  (get-minute [this])
  (get-second [this])
  (get-nano [this])
  (with-year [this year])
  (with-month [this month])
  (with-day-of-month [this day-of-month])
  (with-day-of-year [this day-of-year])
  (with-hour [this hour])
  (with-minute [this minute])
  (with-second [this second])
  (with-nano [this nano-of-second])
  (truncated-to [this unit])
  (plus-years [this years])
  (plus-months [this months])
  (plus-weeks [this weeks])
  (plus-days [this days])
  (plus-hours [this hours])
  (plus-minutes [this minutes])
  (plus-seconds [this seconds])
  (plus-nanos [this nanos])
  (minus-years [this years])
  (minus-months [this months])
  (minus-weeks [this weeks])
  (minus-days [this days])
  (minus-hours [this hours])
  (minus-minutes [this minutes])
  (minus-seconds [this seconds])
  (minus-nanos [this nanos])
  (at-offset [this offset]))

(s/def ::local-date-time #(satisfies? ILocalDateTime %))