(ns jiffy.protocols.offset-date-time
  (:refer-clojure :exclude [format ])
  (:require [clojure.spec.alpha :as s]))

;; https://github.com/unofficial-openjdk/openjdk/tree/cec6bec2602578530214b2ce2845a863da563c3d/src/java.base/share/classes/java/time/OffsetDateTime.java
(defprotocol IOffsetDateTime
  (get-offset [this])
  (to-epoch-second [this])
  (with-offset-same-local [this offset])
  (with-offset-same-instant [this offset])
  (to-local-date-time [this])
  (to-local-date [this])
  (get-year [this])
  (get-month-value [this])
  (get-month [this])
  (get-day-of-month [this])
  (get-day-of-year [this])
  (get-day-of-week [this])
  (to-local-time [this])
  (get-hour [this])
  (get-minute [this])
  (get-second [this])
  (get-nano [this])
  (with-year [this year])
  (with-month [this month])
  (with-day-of-month [this day-of-month])
  (with-day-of-year [this day-of-year])
  (with-hour [this hour])
  (with-minute [this minute])
  (with-second [this second])
  (with-nano [this nano-of-second])
  (truncated-to [this unit])
  (plus-years [this years])
  (plus-months [this months])
  (plus-weeks [this weeks])
  (plus-days [this days])
  (plus-hours [this hours])
  (plus-minutes [this minutes])
  (plus-seconds [this seconds])
  (plus-nanos [this nanos])
  (minus-years [this years])
  (minus-months [this months])
  (minus-weeks [this weeks])
  (minus-days [this days])
  (minus-hours [this hours])
  (minus-minutes [this minutes])
  (minus-seconds [this seconds])
  (minus-nanos [this nanos])
  (format [this formatter])
  (at-zone-same-instant [this zone])
  (at-zone-similar-local [this zone])
  (to-offset-time [this])
  (to-zoned-date-time [this])
  (to-instant [this])
  (is-after [this other])
  (is-before [this other])
  (is-equal [this other]))

(s/def ::offset-date-time #(satisfies? IOffsetDateTime %))