(ns jiffy.parity-tests.duration-test
  (:require [jiffy.big-decimal :as big-decimal]
            [jiffy.duration :as duration]
            [jiffy.math :as math]
            [jiffy.parity-tests.support :refer [test-proto-fn test-proto-fn! test-static-fn test-static-fn!]]))

(test-proto-fn jiffy.duration jiffy.duration/is-zero)
(test-proto-fn jiffy.duration jiffy.duration/is-negative)
(test-proto-fn jiffy.duration jiffy.duration/get-seconds)
(test-proto-fn jiffy.duration jiffy.duration/get-nano)
(test-proto-fn jiffy.duration jiffy.duration/with-seconds)
(test-proto-fn jiffy.duration jiffy.duration/with-nanos)
(test-proto-fn jiffy.duration jiffy.duration/plus)
(test-proto-fn jiffy.duration jiffy.duration/plus-days)
(test-proto-fn jiffy.duration jiffy.duration/plus-hours)
(test-proto-fn jiffy.duration jiffy.duration/plus-minutes)
(test-proto-fn jiffy.duration jiffy.duration/plus-seconds)
(test-proto-fn jiffy.duration jiffy.duration/plus-millis)
(test-proto-fn jiffy.duration jiffy.duration/plus-nanos)
(test-proto-fn jiffy.duration jiffy.duration/minus)
(test-proto-fn jiffy.duration jiffy.duration/minus-days)
(test-proto-fn jiffy.duration jiffy.duration/minus-hours)
(test-proto-fn jiffy.duration jiffy.duration/minus-minutes)
(test-proto-fn jiffy.duration jiffy.duration/minus-seconds)
(test-proto-fn jiffy.duration jiffy.duration/minus-millis)
(test-proto-fn jiffy.duration jiffy.duration/minus-nanos)
(test-proto-fn jiffy.duration jiffy.duration/multiplied-by)
(test-proto-fn jiffy.duration jiffy.duration/divided-by)
(test-proto-fn jiffy.duration jiffy.duration/negated)
(test-proto-fn jiffy.duration jiffy.duration/abs)
(test-proto-fn jiffy.duration jiffy.duration/to-days)
(test-proto-fn jiffy.duration jiffy.duration/to-hours)
(test-proto-fn jiffy.duration jiffy.duration/to-minutes)
(test-proto-fn jiffy.duration jiffy.duration/to-seconds)
(test-proto-fn jiffy.duration jiffy.duration/to-millis)
(test-proto-fn jiffy.duration jiffy.duration/to-nanos)
(test-proto-fn jiffy.duration jiffy.duration/to-days-part)
(test-proto-fn jiffy.duration jiffy.duration/to-hours-part)
(test-proto-fn jiffy.duration jiffy.duration/to-minutes-part)
(test-proto-fn jiffy.duration jiffy.duration/to-seconds-part)
(test-proto-fn jiffy.duration jiffy.duration/to-millis-part)
(test-proto-fn jiffy.duration jiffy.duration/to-nanos-part)

;; (test-proto-fn! jiffy.duration jiffy.duration/truncated-to)

(test-proto-fn jiffy.duration jiffy.time-comparable/compare-to)
(test-proto-fn jiffy.duration jiffy.temporal.temporal-amount/get)

;; (test-proto-fn! jiffy.duration jiffy.temporal.temporal-amount/get-units)
;; (test-proto-fn! jiffy.duration jiffy.temporal.temporal-amount/add-to)
;; (test-proto-fn! jiffy.duration jiffy.temporal.temporal-amount/subtract-from)

;; (test-static-fn! jiffy.duration/between)
;; (test-static-fn! jiffy.duration/parse)
;; (test-static-fn! jiffy.duration/from)
;; (test-static-fn! jiffy.duration/of)
;; (test-static-fn! jiffy.duration/of-nanos)
;; (test-static-fn! jiffy.duration/of-millis)

(test-static-fn jiffy.duration/of-seconds)
(test-static-fn jiffy.duration/of-minutes)
(test-static-fn jiffy.duration/of-hours)
(test-static-fn jiffy.duration/of-days)
