(ns jiffy.parity-tests.instant-test
  (:require [jiffy.parity-tests.support :refer [test-proto-fn test-static-fn]]))

(test-proto-fn jiffy.instant jiffy.instant/getEpochSecond)
(test-proto-fn jiffy.instant jiffy.instant/getNano)
;; (test-proto-fn jiffy.instant jiffy.instant/truncatedTo)
(test-proto-fn jiffy.instant jiffy.instant/plusSeconds)
(test-proto-fn jiffy.instant jiffy.instant/plusMillis)
(test-proto-fn jiffy.instant jiffy.instant/plusNanos)
(test-proto-fn jiffy.instant jiffy.instant/minusSeconds)
(test-proto-fn jiffy.instant jiffy.instant/minusMillis)
(test-proto-fn jiffy.instant jiffy.instant/minusNanos)
(test-proto-fn jiffy.instant jiffy.instant/toEpochMilli)

;; (test-proto-fn jiffy.instant jiffy.instant/atOffset)
;; (test-proto-fn jiffy.instant jiffy.instant/atZone)
;; (test-proto-fn jiffy.instant jiffy.instant/isAfter)
;; (test-proto-fn jiffy.instant jiffy.instant/isBefore)
;; (test-proto-fn jiffy.time-comparable jiffy.instant/compareTo)
;; (test-proto-fn jiffy.temporal.temporal jiffy.instant/with)
;; (test-proto-fn jiffy.temporal.temporal jiffy.instant/plus)
;; (test-proto-fn jiffy.temporal.temporal jiffy.instant/minus)
;; (test-proto-fn jiffy.temporal.temporal jiffy.instant/until)
;; (test-proto-fn jiffy.temporal.temporal-accessor jiffy.instant/isSupported)
;; (test-proto-fn jiffy.temporal.temporal-accessor jiffy.instant/range)
;; (test-proto-fn jiffy.temporal.temporal-accessor jiffy.instant/get)
;; (test-proto-fn jiffy.temporal.temporal-accessor jiffy.instant/getLong)
;; (test-proto-fn jiffy.temporal.temporal-accessor jiffy.instant/query)
;; (test-proto-fn jiffy.temporal.temporal-adjuster jiffy.instant/adjustInto)
;; (test-static-fn jiffy.instant/ofEpochSecond)
;; (test-static-fn jiffy.instant/now)
;; (test-static-fn jiffy.instant/ofEpochMilli)
;; (test-static-fn jiffy.instant/from)
;; (test-static-fn jiffy.local-date/ofEpochDay)
