(ns jiffy.parity-tests.instant-test
  (:require [jiffy.parity-tests.support :refer [test-proto-fn test-proto-fn! test-static-fn test-static-fn!] :as support]))

(test-proto-fn jiffy.instant jiffy.instant/get-epoch-second)
(test-proto-fn jiffy.instant jiffy.instant/get-nano)
;; (test-proto-fn! jiffy.instant jiffy.instant/truncated-to)
(test-proto-fn jiffy.instant jiffy.instant/plus-seconds)
(test-proto-fn jiffy.instant jiffy.instant/plus-millis)
(test-proto-fn jiffy.instant jiffy.instant/plus-nanos)
(test-proto-fn jiffy.instant jiffy.instant/minus-seconds)
(test-proto-fn jiffy.instant jiffy.instant/minus-millis)
(test-proto-fn jiffy.instant jiffy.instant/minus-nanos)
(test-proto-fn jiffy.instant jiffy.instant/to-epoch-milli)
;; (test-proto-fn jiffy.instant jiffy.instant/at-offset)
;; (test-proto-fn jiffy.instant jiffy.instant/at-zone)
(test-proto-fn jiffy.instant jiffy.instant/is-after)
(test-proto-fn jiffy.instant jiffy.instant/is-before)

(test-proto-fn jiffy.instant jiffy.time-comparable/compare-to)

;; (test-proto-fn! jiffy.instant jiffy.temporal.temporal/with)
;; (test-proto-fn! jiffy.instant jiffy.temporal.temporal/plus)
;; (test-proto-fn! jiffy.instant jiffy.temporal.temporal/minus)

(test-proto-fn jiffy.instant jiffy.temporal.temporal/until)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-accessor/is-supported)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-accessor/range)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-accessor/get)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-accessor/get-long)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-accessor/query)
(test-proto-fn jiffy.instant jiffy.temporal.temporal-adjuster/adjust-into)

(test-static-fn jiffy.instant/of-epoch-second)
(test-static-fn jiffy.instant/of-epoch-milli)
;; (test-static-fn! jiffy.instant/now)
;; (test-static-fn jiffy.instant/from)
