(ns jiffy.parity-tests.local-time-test
  (:require [clojure.spec.alpha :as s]
            [clojure.spec.gen.alpha :as gen]
            [jiffy.parity-tests.support :refer [test-proto-fn test-proto-fn!]]))

(test-proto-fn jiffy.local-time jiffy.local-time/toNanoOfDay)
(test-proto-fn jiffy.local-time jiffy.local-time/toSecondOfDay)
(test-proto-fn jiffy.local-time jiffy.local-time/getHour)
(test-proto-fn jiffy.local-time jiffy.local-time/getMinute)
(test-proto-fn jiffy.local-time jiffy.local-time/getSecond)
(test-proto-fn jiffy.local-time jiffy.local-time/getNano)
(test-proto-fn jiffy.local-time jiffy.local-time/withHour)
(test-proto-fn jiffy.local-time jiffy.local-time/withMinute)
(test-proto-fn jiffy.local-time jiffy.local-time/withSecond)
(test-proto-fn jiffy.local-time jiffy.local-time/withNano)
;;(test-proto-fn jiffy.local-time jiffy.local-time/truncatedTo)
(test-proto-fn jiffy.local-time jiffy.local-time/plusHours)
(test-proto-fn jiffy.local-time jiffy.local-time/plusMinutes)
(test-proto-fn jiffy.local-time jiffy.local-time/plusSeconds)
(test-proto-fn jiffy.local-time jiffy.local-time/plusNanos)
(test-proto-fn jiffy.local-time jiffy.local-time/minusHours)
(test-proto-fn jiffy.local-time jiffy.local-time/minusMinutes)
(test-proto-fn jiffy.local-time jiffy.local-time/minusSeconds)
(test-proto-fn jiffy.local-time jiffy.local-time/minusNanos)
;;(test-proto-fn jiffy.local-time jiffy.local-time/format)
;;(test-proto-fn jiffy.local-time jiffy.local-time/atDate)
;;(test-proto-fn jiffy.local-time jiffy.local-time/atOffset)
;;(test-proto-fn jiffy.local-time jiffy.local-time/toEpochSecond)
(test-proto-fn jiffy.local-time jiffy.local-time/isAfter)
(test-proto-fn jiffy.local-time jiffy.local-time/isBefore)
