(ns jiffy.parity-tests.period-test
  (:require [jiffy.parity-tests.support :refer [test-proto-fn test-proto-fn! test-static-fn test-static-fn!]]))

(test-proto-fn jiffy.period jiffy.protocols.period/get-years)
(test-proto-fn jiffy.period jiffy.protocols.period/get-months)
(test-proto-fn jiffy.period jiffy.protocols.period/get-days)
(test-proto-fn jiffy.period jiffy.protocols.period/with-years)
(test-proto-fn jiffy.period jiffy.protocols.period/with-months)
(test-proto-fn jiffy.period jiffy.protocols.period/with-days)
(test-proto-fn jiffy.period jiffy.protocols.period/plus-years)
(test-proto-fn jiffy.period jiffy.protocols.period/plus-months)
(test-proto-fn jiffy.period jiffy.protocols.period/plus-days)
(test-proto-fn jiffy.period jiffy.protocols.period/minus-years)
(test-proto-fn jiffy.period jiffy.protocols.period/minus-months)
(test-proto-fn jiffy.period jiffy.protocols.period/minus-days)
(test-proto-fn jiffy.period jiffy.protocols.period/to-total-months)
;; (test-proto-fn! jiffy.period jiffy.protocols.chrono.chrono-period/get-chronology)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/is-zero)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/is-negative)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/plus)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/minus)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/multiplied-by)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/negated)
(test-proto-fn jiffy.period jiffy.protocols.chrono.chrono-period/normalized)
(test-proto-fn jiffy.period jiffy.protocols.temporal.temporal-amount/get)
(test-proto-fn jiffy.period jiffy.protocols.temporal.temporal-amount/get-units)
(test-proto-fn jiffy.period jiffy.protocols.temporal.temporal-amount/add-to)
(test-proto-fn jiffy.period jiffy.protocols.temporal.temporal-amount/subtract-from)

(test-static-fn jiffy.period/from)
(test-static-fn jiffy.period/of-years)
(test-static-fn jiffy.period/of-months)
(test-static-fn jiffy.period/of-weeks)
(test-static-fn jiffy.period/of-days)
(test-static-fn jiffy.period/of)
(test-static-fn jiffy.period/parse)
;; (test-static-fn! jiffy.period/between)
